"use client";

import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import ErrorBoundary from "@/components/shared/CustomErrorBoundary";
import AuthContextProvider from "@/context/AuthContext";
import { RecoilRoot } from "recoil";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next-Flix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className}>
        <AuthContextProvider>
          <RecoilRoot>
            <ErrorBoundary>
              {children}
              <Toaster />
            </ErrorBoundary>
          </RecoilRoot>
        </AuthContextProvider>
      </body>
    </html>
  );
}
